### ISSUE TITLE
Interaction Data Layers bug w/ geojson "name" prop"

### ISSUE THREAD

**Issue by uwcart** [uwcartlab/mapstudy#2]
Overlay operator broken with geojson exported from QGIS- has "name" property at FeatureCollection level, _defaults overwrites dataLayer name property from config file with this property at line 1941 when creating leaflet layer.

**Comment by cartobaldrica** [comment]
Added dataLayer name property as new attribute passed to model when leaflet layer is created. Storing the name as a new attribute prevents overwriting.
